title: "felipejoglar.dev"
description: "Programmer"
url: https://felipejoglar.github.io
image: /assets/images/global/opengraph.png
github: felipejoglar
repository: felipejoglar/felipejoglar.github.io
markdown: kramdown
highlighter: rouge

permalink: /:title/

collections:
  authors:
    output: true
  series:
    output: true

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope: 
      type: "authors"
    values:
      layout: "author"
  - scope: 
      type: "series"
    values:
      layout: "series"

exclude:
  - README.md
  - felipejoglar.drawio

sass:
  style: compressed

plugins:
  - jekyll-redirect-from

redirect_from:
  json: false