title: "felipejoglar.dev"
description: "Programmer"
url: https://felipejoglar.github.io
image: /assets/images/opengraph.png
github: felipejoglar
repository: felipejoglar/felipejoglar.github.io
markdown: kramdown
highlighter: rouge

permalink: /:title/

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"

exclude:
  - README.md

sass:
  style: compressed

redirect_from:
  json: false

collections:
  authors:
    output: true
  series:
    output: true